#!/bin/sh

set -e

function usage() {
  bold=$(tput bold)
  normal=$(tput sgr0)
  cat << EOF

${bold}NAME${normal}
       git-merge-branch - Merge the current branch into the master branch

${bold}SYNOPSIS${normal}
       git merge-branch

EOF
}

# actually parse the options and do stuff
while [[ $1 = -?* ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
    ;;
    *) ;;
  esac
  shift
done

currentBranch=$(git rev-parse --abbrev-ref HEAD)
defaultBranch=$(git symbolic-ref refs/remotes/origin/HEAD | cut -d "/" -f 4)

if [ "${currentBranch}" == "$defaultBranch" ]; then
  echo "Error: Branch currently set to Default Branch: $defaultBranch"
  usage
fi

upstream=$(git rev-parse --abbrev-ref @{upstream} 2>/dev/null)

echo '[INFO] Syncing remotes and branches'
hub sync
echo "[INFO] git checkout $defaultBranch"
git checkout $defaultBranch
echo "[INFO] Merge branch: ${currentBranch}"
git merge --no-ff --no-edit ${currentBranch}
git push $upstream $defaultBranch

echo "[INFO] Delete local and remote branch '$currentBranch' from '${upstream}'"
# Delete the remote branch if it lives in origin
git push --delete $upstream ${currentBranch}

# Delete the pull request branch locally
git branch -d ${currentBranch}


