#!/bin/sh

set -e

function usage() {
  bold=$(tput bold)
  normal=$(tput sgr0)
  cat << EOF

${bold}NAME${normal}
       git-push-branch - Push the current branch and track remote

${bold}SYNOPSIS${normal}
       git push-branch

EOF
}

# actually parse the options and do stuff
while [[ $1 = -?* ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
    ;;
    *) ;;
  esac
  shift
done

branch=$(git rev-parse --abbrev-ref HEAD)
upstream=$(git rev-parse --abbrev-ref @{upstream} 2>/dev/null)

if [[ $? == 0 ]]; then
  echo "branch '$branch' tracks '$upstream'"
  git push
else
  echo "branch '$branch' has no upstream configured"
  git push -u origin $branch
fi


