#!/bin/bash

set -ex

function usage() {
  bold=$(tput bold)
  normal=$(tput sgr0)
  cat << EOF

${bold}NAME${normal}
       git-create-pr - Create a pull request from current branch

${bold}SYNOPSIS${normal}
       git create-pr

EOF
}

# actually parse the options and do stuff
while [[ $1 = -?* ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
    ;;
    *) ;;
  esac
  shift
done

#echo "branch..."
branch=$(git rev-parse --abbrev-ref HEAD)
#echo "upstream..."
#upstream=$( git rev-parse --abbrev-ref @{upstream} || "" )

#echo "does it track?"
#if [[ "${upstream}" != "" ]]; then
  #echo "branch '$branch' tracks '$upstream'"
  #git push
#else
  #echo "branch '$branch' has no upstream configured"
  git push -u origin $branch
#fi

hub pull-request

